CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(128) NOT NULL,
  display_name VARCHAR(64),
  role VARCHAR(32) NOT NULL DEFAULT 'USER',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_username ON sys_user(username);

CREATE TABLE IF NOT EXISTS rule_definition (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_code VARCHAR(64) NOT NULL,
  rule_name VARCHAR(128) NOT NULL,
  category VARCHAR(32) NOT NULL,
  business_line VARCHAR(64) NOT NULL,
  description VARCHAR(512),
  sensitive BOOLEAN NOT NULL DEFAULT FALSE,
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  owner VARCHAR(64) NOT NULL,
  current_version INT,
  gray_version INT,
  gray_percent INT DEFAULT 0,
  regulatory_ref VARCHAR(128),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_rule_definition_code ON rule_definition(rule_code);
CREATE INDEX IF NOT EXISTS idx_rule_definition_category ON rule_definition(category);

CREATE TABLE IF NOT EXISTS rule_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_code VARCHAR(64) NOT NULL,
  version INT NOT NULL,
  status VARCHAR(32) NOT NULL,
  drl_content CLOB NOT NULL,
  visual_model CLOB,
  checksum VARCHAR(64) NOT NULL,
  effective_from TIMESTAMP,
  effective_to TIMESTAMP,
  created_by VARCHAR(64) NOT NULL,
  approved_by VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_rule_version ON rule_version(rule_code, version);
CREATE INDEX IF NOT EXISTS idx_rule_version_status ON rule_version(status);
CREATE INDEX IF NOT EXISTS idx_rule_version_rule_code ON rule_version(rule_code);

CREATE TABLE IF NOT EXISTS rule_execution_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trace_id VARCHAR(64) NOT NULL,
  rule_code VARCHAR(64) NOT NULL,
  version INT NOT NULL,
  scenario VARCHAR(64) NOT NULL,
  decision VARCHAR(64) NOT NULL,
  hit_rules VARCHAR(1024),
  elapsed_ms BIGINT NOT NULL,
  request_snapshot CLOB,
  response_snapshot CLOB,
  operator VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rule_exec_trace ON rule_execution_log(trace_id);
CREATE INDEX IF NOT EXISTS idx_rule_exec_rule_code ON rule_execution_log(rule_code);
CREATE INDEX IF NOT EXISTS idx_rule_exec_created_at ON rule_execution_log(created_at);

CREATE TABLE IF NOT EXISTS rule_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_code VARCHAR(64) NOT NULL,
  version INT,
  action VARCHAR(64) NOT NULL,
  operator VARCHAR(64) NOT NULL,
  reason VARCHAR(512),
  ip_address VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rule_audit_rule_code ON rule_audit_log(rule_code);
CREATE INDEX IF NOT EXISTS idx_rule_audit_created_at ON rule_audit_log(created_at);

