FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/rule-engine-ui/package.json ./
RUN npm install
COPY frontend/rule-engine-ui ./
RUN npm run build

FROM nginx:1.27-alpine
COPY frontend/rule-engine-ui/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80

